### PR TITLE
Rewrite to ES6 class Component. Up libs.

### PR DESCRIPTION
**Pull request by DimitryDushkin**

### CODE REVIEW

**Comment by DimitryDushkin** [comment]
Are there anybody using react without transpilation and es2015+?)

**Comment by devlato** [comment]
@DimitryDushkin the code amount here is very small, so I preferred to skip the building process and implement lib with ES5 for compatibility. No need to bring dependencies and babel runtimes for such small amount of code.

**Comment by DimitryDushkin** [comment]
Babel is only needed for old browsers. As you can see it passes all tests on node 6+.
Also there is no real projects with react and without building process. There is always a need to resolve modules and bundle it. `module.exports` in code just throw error in browser.

Anyway, it's your repo, so you can reject it. I'll just copy paste it to my project. =)

**Comment by DimitryDushkin** [comment]
And new react 16 will not support React.createClass, so lib won't work with it.

**Comment by DimitryDushkin** [comment]
Anyway, thank you for great lib. 👍

**Pull request closed without merging**
